apiVersion: v1
kind: Service
metadata:
  name: auth-data-access-service
  namespace: rml
spec:
  selector:
    app: auth-data-access
  ports:
    - name: port1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: port2
      protocol: TCP
      port: 443
      targetPort: 443
