apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-app-auto-scaler
  namespace: rml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50