apiVersion: v1
kind: Service
metadata:
  name: object-recognition-service
  namespace: rml
spec:
  selector:
    app: object-recognition
  ports:
    - name: port1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: port2
      protocol: TCP
      port: 443
      targetPort: 443
