apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: object-recognition-auto-scaling
  namespace: rml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: object-recognition-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
