name: 🐋 Kubernetes Config | Automatic Redeployment

env:
  workdir: k8s/config
  KUBE_HOST: ${{ secrets.KUBE_HOST }}
  KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

on:
  push:
    paths: [ "k8s/config/**", ".github/workflows/kubernetes-config.yml" ]
    branches: main

jobs:
  deploy:
    name: Deploy kubernetes config
    runs-on: self-hosted
    steps:
    - uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          microk8s kubectl delete -R -f repo/k8s/config
          rm -rf repo
          git clone https://github.com/Alpacron/antivalor repo
          microk8s kubectl apply -R -f repo/k8s/config
