name: ☁ Object Recognition Service | Sonar

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_OBJECT_RECOGNITION }}
  workdir: services/object-recognition

on:
  push:
    paths: [ "services/object-recognition/**", ".github/workflows/object-recognition-service-sonar.yml" ]
    branches: main
  pull_request:
    paths: [ "services/object-recognition/**", ".github/workflows/object-recognition-service-sonar.yml" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Test
        run: tox -e py
      - uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ env.workdir }}
