name: 🐋 Object Recognition Service | Docker

env:
  workdir: services/object-recognition

on:
  push:
    paths: [ "services/object-recognition/**", ".github/workflows/object-recognition-service-docker-image.yml" ]
    branches: main

jobs:
  build:
    name: Build and Push Image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t alpacron/object-recognition:latest $workdir
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push alpacron/object-recognition

  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions-hub/kubectl@master
      env:
        KUBE_HOST: ${{ secrets.KUBE_HOST }}
        KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      with:
        args: rollout restart deployment playlist-app
    - name: deploy
      run: echo "deploying started"
