name: ☁ Object Recognition Service | Sonar

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_OBJECT_RECOGNITION }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  workdir: services/object-recognition

on:
  push:
    paths: [ "services/object-recognition/**", ".github/workflows/object-recognition-service-sonar.yml" ]
    branches: main
  pull_request:
    paths: [ "services/object-recognition/**", ".github/workflows/object-recognition-service-sonar.yml" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
        working-directory: ${{ env.workdir }}
      - name: Test
        run: tox -e py
        working-directory: ${{ env.workdir }}
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ${{ env.workdir }}

  deploy:
    name: Analyse
    runs-on: self-hosted
    needs: build
    steps:
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ${{ env.workdir }}
