name: 🐋 State Service | Docker

env:
  workdir: services/state

on:
  push:
    paths: [ "${{ env.workdir }}/**", ".github/workflows/state-service-docker-image.yml" ]
    branches: main

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t alpacron/state:latest $workdir
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push alpacron/state
